run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell


version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
